(in-package :prolog)

(defun traceall ()
  (esrap:trace-rule 'prolog::Prolog)		
  (esrap:trace-rule 'prolog::Fact)
  (esrap:trace-rule 'prolog::CompoundQuery	)
  (esrap:trace-rule 'prolog::Rule		)
  (esrap:trace-rule 'prolog::Query		)
  (esrap:trace-rule 'prolog::Head		)
  (esrap:trace-rule 'prolog::Body		)
  (esrap:trace-rule 'prolog::Goal		)
  (esrap:trace-rule 'prolog::Structure	)
  (esrap:trace-rule 'prolog::Functor		)
  (esrap:trace-rule 'prolog::Arith		)
  (esrap:trace-rule 'prolog::Equ		)
  (esrap:trace-rule 'prolog::Expr		)
  (esrap:trace-rule 'prolog::Term		)
  (esrap:trace-rule 'prolog::Factor		)
  (esrap:trace-rule 'prolog::Primary		)
  (esrap:trace-rule 'prolog::RELOP		)
  (esrap:trace-rule 'prolog::PLOP		)
  (esrap:trace-rule 'prolog::MULOP		)
  (esrap:trace-rule 'prolog::Predicate	)
  (esrap:trace-rule 'prolog::Args		)
  (esrap:trace-rule 'prolog::Fundament	)
  (esrap:trace-rule 'prolog::List		)
  (esrap:trace-rule 'prolog::Variable	)
  (esrap:trace-rule 'prolog::Atom		)
  (esrap:trace-rule 'prolog::Small-Ident	)
  (esrap:trace-rule 'prolog::Special		)
  (esrap:trace-rule 'prolog::Number		)
  (esrap:trace-rule 'prolog::Integer		)
  (esrap:trace-rule 'prolog::Unsigned-Int	)
  (esrap:trace-rule 'prolog::Float		)
  (esrap:trace-rule 'prolog::Unsigned-Float	)
  (esrap:trace-rule 'prolog::Exponent	)
  (esrap:trace-rule 'prolog::String		)
  (esrap:trace-rule 'prolog::SQString	)
  (esrap:trace-rule 'prolog::DQString	)
  (esrap:trace-rule 'prolog::Char-List	)
  (esrap:trace-rule 'prolog::Char)
  (esrap:trace-rule 'prolog::Char1		)
  (esrap:trace-rule 'prolog::Char2)
  (esrap:trace-rule 'prolog::Sign		)
  (esrap:trace-rule 'prolog::Cut		)
  (esrap:trace-rule 'prolog::IS		)
  (esrap:trace-rule 'prolog::LPAR		)
  (esrap:trace-rule 'prolog::RPAR		)
  (esrap:trace-rule 'prolog::LBRACKET	)
  (esrap:trace-rule 'prolog::RBRACKET	)
  (esrap:trace-rule 'prolog::COMMA		)
  (esrap:trace-rule 'prolog::Spacing 	)
  (esrap:trace-rule 'prolog::Comment 	)
  (esrap:trace-rule 'prolog::Line-Comment 	)
  (esrap:trace-rule 'prolog::Space   	)
  (esrap:trace-rule 'prolog::EndOfLine 	)
  (esrap:trace-rule 'prolog::EndOfFile 	)
  (esrap:trace-rule 'prolog::RuleWithBody 	)
  (esrap:trace-rule 'prolog::RuleNoBody)
  )


(defun untraceall ()
  (esrap:untrace-rule 'prolog::Prolog)		
  (esrap:untrace-rule 'prolog::Fact)
  (esrap:untrace-rule 'prolog::CompoundQuery	)
  (esrap:untrace-rule 'prolog::Rule		)
  (esrap:untrace-rule 'prolog::Query		)
  (esrap:untrace-rule 'prolog::Head		)
  (esrap:untrace-rule 'prolog::Body		)
  (esrap:untrace-rule 'prolog::Goal		)
  (esrap:untrace-rule 'prolog::Structure	)
  (esrap:untrace-rule 'prolog::Functor		)
  (esrap:untrace-rule 'prolog::Arith		)
  (esrap:untrace-rule 'prolog::Equ		)
  (esrap:untrace-rule 'prolog::Expr		)
  (esrap:untrace-rule 'prolog::Term		)
  (esrap:untrace-rule 'prolog::Factor		)
  (esrap:untrace-rule 'prolog::Primary		)
  (esrap:untrace-rule 'prolog::RELOP		)
  (esrap:untrace-rule 'prolog::PLOP		)
  (esrap:untrace-rule 'prolog::MULOP		)
  (esrap:untrace-rule 'prolog::Predicate	)
  (esrap:untrace-rule 'prolog::Args		)
  (esrap:untrace-rule 'prolog::Fundament	)
  (esrap:untrace-rule 'prolog::List		)
  (esrap:untrace-rule 'prolog::Variable	)
  (esrap:untrace-rule 'prolog::Atom		)
  (esrap:untrace-rule 'prolog::Small-Ident	)
  (esrap:untrace-rule 'prolog::Special		)
  (esrap:untrace-rule 'prolog::Number		)
  (esrap:untrace-rule 'prolog::Integer		)
  (esrap:untrace-rule 'prolog::Unsigned-Int	)
  (esrap:untrace-rule 'prolog::Float		)
  (esrap:untrace-rule 'prolog::Unsigned-Float	)
  (esrap:untrace-rule 'prolog::Exponent	)
  (esrap:untrace-rule 'prolog::String		)
  (esrap:untrace-rule 'prolog::SQString	)
  (esrap:untrace-rule 'prolog::DQString	)
  (esrap:untrace-rule 'prolog::Char-List	)
  (esrap:untrace-rule 'prolog::Char)
  (esrap:untrace-rule 'prolog::Char1		)
  (esrap:untrace-rule 'prolog::Char2)
  (esrap:untrace-rule 'prolog::Sign		)
  (esrap:untrace-rule 'prolog::Cut		)
  (esrap:untrace-rule 'prolog::IS		)
  (esrap:untrace-rule 'prolog::LPAR		)
  (esrap:untrace-rule 'prolog::RPAR		)
  (esrap:untrace-rule 'prolog::LBRACKET	)
  (esrap:untrace-rule 'prolog::RBRACKET	)
  (esrap:untrace-rule 'prolog::COMMA		)
  (esrap:untrace-rule 'prolog::Spacing 	)
  (esrap:untrace-rule 'prolog::Comment 	)
  (esrap:untrace-rule 'prolog::Line-Comment 	)
  (esrap:untrace-rule 'prolog::Space   	)
  (esrap:untrace-rule 'prolog::EndOfLine 	)
  (esrap:untrace-rule 'prolog::EndOfFile 	)
  (esrap:untrace-rule 'prolog::RuleWithBody)
  (esrap:untrace-rule 'prolog::RuleNoBody)
  )
